[package]
name = "day10"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
description.workspace = true
publish.workspace = true

[dependencies]
fraction = "0.15.3"

[dev-dependencies]
rstest.workspace = true
