[package]
name = "day09"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
description.workspace = true
publish.workspace = true

[dependencies]
grid.workspace = true
aoc_helper.workspace = true