[package]
name = "day25"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
description.workspace = true
publish.workspace = true

[dependencies]
intcode.workspace = true
nom.workspace = true
fxhash.workspace = true
itertools.workspace = true