default_job = "clippy"

[jobs.run_p1]
command = ["cargo", "run", "--bin", "p1"]
need_stdout = true
allow_warnings = true

[jobs.run_p2]
command = ["cargo", "run", "--bin", "p2"]
need_stdout = true
allow_warnings = true

[jobs.test_p1]
command = ["cargo", "test", "part1"]
need_stdout = true
allow_warnings = true

[jobs.test_p2]
command = ["cargo", "test", "part2"]
need_stdout = true
allow_warnings = true

[jobs.print_input]
command = ["batcat", "-p", "src/input.txt"]
need_stdout = true
default_watch = false

[keybindings]
1 = "job:run_p1"
2 = "job:run_p2"
3 = "job:test_p1"
4 = "job:test_p2"
5 = "job:print_input"
