[package]
name = "day17"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
description.workspace = true
publish.workspace = true

[dependencies]
md5.workspace = true
rstest.workspace = true
aoc_helper.workspace = true
