[package]
name = "day04"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
description.workspace = true
publish.workspace = true

[dependencies]
md5 = "0.8.0"
rstest.workspace = true
