[package]
name = "aoc_helper"
version = "0.1.0"
edition = "2024"
authors = ["Vương Kiến Thanh <thanhstardust@outlook.com>"]
rust-version = "1.91.0"
description = "AOC helper"
publish = false

[dependencies]
nom = "~8.0.0"
num-traits = "0.2.19"
fxhash = "0.2.1"
itertools = "~0.14"
