[package]
name = "day16"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
description.workspace = true
publish.workspace = true

[dependencies]

[dev-dependencies]
rstest.workspace = true
