[package]
name = "day03"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
description.workspace = true
publish.workspace = true

[dependencies]
rayon.workspace = true
[dev-dependencies]
rstest.workspace = true
